Tum: derle calistir

derle:
	g++ -I ./include/ -o ./lib/Factorial.o -c ./src/Factorial.cpp
	g++ -I ./include/ -o ./lib/ArrayList.o -c ./src/ArrayList.cpp
	g++ -I ./include/ -o ./bin/Test ./lib/Factorial.o ./lib/ArrayList.o ./src/Test.cpp
	
calistir:
	./bin/Test